<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cml</string>
	</array>
	<key>name</key>
	<string>Chris Markup Language (CML)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\t\t\t+\-\s</string>
			<key>comment</key>
			<string>Unfinished task level 4</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>todo.incomplete4.cml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#project</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\t\t\-\s</string>
			<key>comment</key>
			<string>Unfinished task level 3</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>todo.incomplete3.cml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#project</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\t\-\s</string>
			<key>comment</key>
			<string>Unfinished task level 2</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>todo.incomplete2.cml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#project</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\-\s</string>
			<key>comment</key>
			<string>Unfinished task level 1</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>todo.incomplete1.cml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#project</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\*\s</string>
			<key>comment</key>
			<string>In-progress task</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>todo.inprogress.cml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#project</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\+\s</string>
			<key>comment</key>
			<string>Finished task</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>todo.complete.cml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#project</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*x\s</string>
			<key>comment</key>
			<string>Dead task</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>todo.dead.cml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#project</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\?\s</string>
			<key>comment</key>
			<string>Unsure task</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>todo.unsure.cml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#project</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\=\=\=\s</string>
			<key>comment</key>
			<string>Heading 1</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>todo.heading.1.cml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#project</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\=\=\s</string>
			<key>comment</key>
			<string>Heading 2</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>todo.heading.2.cml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#project</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\=\s</string>
			<key>comment</key>
			<string>Major task</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>todo.major.cml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#project</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\#\s</string>
			<key>comment</key>
			<string>Bugfix task</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>todo.bug.cml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#project</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*\!\s</string>
			<key>comment</key>
			<string>Alert task</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>todo.alert.cml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#context</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#project</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#command</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#old</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Context</string>
			<key>match</key>
			<string>(\@\S+)</string>
			<key>name</key>
			<string>context.cml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Project</string>
			<key>match</key>
			<string>(\+\S+)</string>
			<key>name</key>
			<string>project.cml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Command</string>
			<key>match</key>
			<string>(`[^`]+`)</string>
			<key>name</key>
			<string>command.cml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Old</string>
			<key>match</key>
			<string>(~[^~]+~)</string>
			<key>name</key>
			<string>old.cml</string>
		</dict>
		<dict>
			<key>link</key>
			<string>Link</string>
			<key>match</key>
			<string>(\S+://\S+)</string>
			<key>name</key>
			<string>link.cml</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>String</string>
			<key>match</key>
			<string>.</string>
			<key>name</key>
			<string>todo.string.cml</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>context</key>
		<dict>
			<key>match</key>
			<string>(\@\S+)</string>
			<key>name</key>
			<string>context.cml</string>
		</dict>
		<key>project</key>
		<dict>
			<key>match</key>
			<string>(\+\S+)</string>
			<key>name</key>
			<string>project.cml</string>
		</dict>
		<key>command</key>
		<dict>
			<key>match</key>
			<string>(`[^`]+`)</string>
			<key>name</key>
			<string>command.cml</string>
		</dict>
		<key>old</key>
		<dict>
			<key>match</key>
			<string>(~[^~]+~)</string>
			<key>name</key>
			<string>old.cml</string>
		</dict>
		<key>link</key>
		<dict>
			<key>match</key>
			<string>(\S+://\S+)</string>
			<key>name</key>
			<string>link.cml</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.cml</string>
	<key>uuid</key>
	<string>09210bf3-2b16-47ca-a42e-4dee50cd6535</string>
</dict>
</plist>
